/* RU -> EN phrase map for product/docs content */
window.AkmanPhrases = {
  "Средства измерений": "Measuring instruments",
  "Расходомеры": "Flowmeters",
  "Ротаметры": "Rotameters",
  "Уровнемеры": "Level gauges",
  "Запорно-регулирующая арматура": "Shut-off and control valves",
  "Арматура трубопроводная": "Pipeline valves",
  "Арматура промышленная трубопроводная": "Industrial pipeline valves",
  "Арматура": "Valves",
  "ВКУ": "Tower internals",
  "Внутренние контактные устройства": "Tower internals",
  "Внутренние контактные устройства (ВКУ)": "Tower internals",
  "Вихревые": "Vortex",
  "Вихревые расходомеры": "Vortex flowmeters",
  "Вихревые расходомеры FLSTV": "FLSTV vortex flowmeters",
  "Расходомеры-счетчики вихревые FLSTV": "FLSTV vortex flowmeters",
  "Расходомеры-счетчики вихревые FLSTV FK60": "FLSTV FK60 vortex flowmeters",
  "Расходомеры-счетчики вихревые FLSTV FK60 (с Bluetooth)": "FLSTV FK60 vortex flowmeters (Bluetooth)",
  "Расходомеры-счетчики вихревые FLSTV FK62": "FLSTV FK62 vortex flowmeters",
  "FK60 (с Bluetooth)": "FK60 (Bluetooth)",
  "Клапаны регулирующие": "Control valves",
  "Клапаны регулирующие 2-х ходовые": "Two-way control valves",
  "Клапаны регулирующие 3-х ходовые": "Three-way control valves",
  "Клапаны регулирующие угловые": "Angle control valves",
  "Клапаны регулирующие серий SV100, SV200, SV300": "Control valves, SV100 / SV200 / SV300 series",
  "Клапаны (вентили)": "Globe valves",
  "Клапаны обратные": "Check valves",
  "Клапаны предохранительные": "Pressure relief valves",
  "Регуляторы давления": "Pressure regulators",
  "Краны шаровые": "Ball valves",
  "Краны пробковые": "Plug valves",
  "Краны шаровые, краны пробковые": "Ball and plug valves",
  "Затворы дисковые": "Butterfly valves",
  "Затворы дисковые, задвижки": "Butterfly and gate valves",
  "Задвижки": "Gate valves",
  "Клапаны (вентили), клапаны обратные": "Globe and check valves",
  "Конденсатоотводчики": "Steam traps",
  "Заглушки поворотные": "Spectacle blinds",
  "Фильтры": "Strainers",
  "Насадки башенные": "Tower packings",
  "Насадки регулярные": "Structured packings",
  "Насадки регулярные 1-го поколения": "1st-generation structured packings",
  "Насадки регулярные 2-го поколения": "2nd-generation structured packings",
  "Насадки регулярные 3-го поколения": "3rd-generation structured packings",
  "Насадки хаотичные": "Random packings",
  "Насадки": "Packings",
  "Тарелки ректификационной колонны": "Distillation column trays",
  "Внутренние устройства башенные с насадкой": "Packed tower internals",
  "Внутренние устройства разделения": "Separation internals",
  "Внутренние устройства реактора": "Reactor internals",
  "Запорно-регулирующая арматура": "Control and shut-off valves",
  "Расходомеры, ротаметры и уровнемеры": "Flowmeters, rotameters and level gauges",
  "Регулирующая и запорная арматура": "Control and shut-off valves",
  "Насадки, тарелки и устройства колонн": "Packings, trays and column internals",
  "Вихревые, электромагнитные, ультразвуковые и массовые": "Vortex, electromagnetic, ultrasonic and mass",
  "с компенсацией температуры и давления": "with temperature and pressure compensation",
  "с компенсацией температуры и давления, Bluetooth": "with temperature and pressure compensation, Bluetooth",
  "Подберём оборудование под вашу задачу": "We will select equipment for your application",
  "Подберём оборудование под задачу объекта": "We will select equipment for your facility",
  "Опишите параметры — подготовим коммерческое предложение.": "Describe the parameters — we will prepare a quotation.",
  "Опишите параметры — подготовим технико-коммерческое предложение.": "Describe the parameters — we will prepare a technical and commercial quotation.",
  "Доступно по запросу": "Available on request",
  "Запросить коммерческое предложение": "Request a quotation",
  "Технические характеристики": "Technical specifications",
  "Главная": "Home",
  "Наши продукты": "Our products",
  "Открыть": "Open",
  "К разделу": "Back to section",
  "Подробнее": "Details",
  "Перейти": "Open",
  "Консультация": "Consultation",
  "Запросить ТКП": "Request a quotation",
  "Запросить": "Request",
  "Позвонить": "Call",
  "Смотреть": "View",
  "Смотреть →": "View →",
  "Смотреть модели": "View models",
  "Рабочая среда": "Process medium",
  "Диаметр номинальный для жидкости, мм": "Nominal diameter for liquid, mm",
  "Диаметр номинальный для газа и пара, мм": "Nominal diameter for gas and steam, mm",
  "Диаметр номинальный для газа, мм": "Nominal diameter for gas, mm",
  "Диаметр номинальный, мм": "Nominal diameter, mm",
  "Давление номинальное, МПа": "Nominal pressure, MPa",
  "Давление номинальное, ASME Class": "Nominal pressure, ASME Class",
  "Давление номинальное": "Nominal pressure",
  "Температура рабочей среды, ℃": "Process temperature, °C",
  "Температура окружающей среды, ℃": "Ambient temperature, °C",
  "Тип присоединения": "Connection type",
  "Материал": "Material",
  "Материалы": "Materials",
  "Материалы корпуса": "Body materials",
  "Диапазон расхода жидкости, м/с": "Liquid flow velocity range, m/s",
  "Диапазон расхода газа, м/с": "Gas flow velocity range, m/s",
  "Диапазон расхода пара, м/с": "Steam flow velocity range, m/s",
  "Маркировка взрывозащиты": "Explosion protection marking",
  "Питание": "Power supply",
  "Выходной сигнал": "Output signal",
  "Число Рейнольдса": "Reynolds number",
  "Конструкция": "Design",
  "Конструкция затвора": "Disc / gate design",
  "Конструкция клапана": "Valve design",
  "Класс герметичности": "Tightness class",
  "Класс протечки (опция)": "Leakage class (option)",
  "Класс протечки (стандарт)": "Leakage class (standard)",
  "Стандарт": "Standard",
  "Стандарты": "Standards",
  "Присоединение": "Connection",
  "Условный проход": "Nominal size",
  "Исполнение": "Design",
  "Тип": "Type",
  "Серия": "Series",
  "Тип арматуры": "Valve type",
  "Тип затвора": "Disc type",
  "Тип затворной части": "Closure type",
  "Тип клапана": "Valve type",
  "Тип крышки": "Bonnet type",
  "Управление": "Actuation",
  "жидкость, газ, пар": "liquid, gas, steam",
  "жидкость, газ": "liquid, gas",
  "фланцевый, межфланцевый": "flanged, wafer",
  "фланцевое": "flanged",
  "фланцевое; сварное": "flanged; welded",
  "фланцевое; сварное; резьбовое": "flanged; welded; threaded",
  "24 В, постоянный ток": "24 V DC",
  "токовый от 4 до 20 мА, частотно-импульсный, протокол HART, Modbus RS 485": "4–20 mA, frequency/pulse, HART, Modbus RS-485",
  "SS304 (стандартный), SS316 (опция)": "SS304 (standard), SS316 (option)",
  "Декларации": "Declarations",
  "Сертификаты": "Certificates",
  "Тип продукции": "Product type",
  "РусХлорСерт": "RusKhlorSert",
  "Тип СИ": "MI type approval",
  "Декларации о соответствии": "Declarations of conformity",
  "Сертификаты соответствия": "Certificates of conformity",
  "Сертификаты на тип продукции": "Product type certificates",
  "Сертификаты РусХлорСерт": "RusKhlorSert certificates",
  "Свидетельства об утверждении типа СИ": "Measuring instrument type approval certificates",
  "Сброс": "Reset",
  "Просмотр документа": "Document viewer",
  "Закрыть": "Close",
  "Масштаб": "Zoom",
  "Отдалить": "Zoom out",
  "Приблизить": "Zoom in",
  "Сбросить масштаб": "Reset zoom",
  "Разделы документов": "Document sections",
  "Кольца Палля (металлические)": "Pall rings (metal)",
  "Кольца Палля (пластиковые)": "Pall rings (plastic)",
  "Кольца Рашига (керамические)": "Raschig rings (ceramic)",
  "Кольца Рашига (металлические)": "Raschig rings (metal)",
  "Кольца Рашига (углеродные)": "Raschig rings (carbon)",
  "Звездообразные": "Star-shaped",
  "М-образные": "M-shaped",
  "Т-образные": "T-shaped",
  "Металлические": "Metal",
  "Регулярные": "Structured",
  "Опорные решетки": "Support grids",
  "Опоры насадочные": "Packing supports",
  "Ограничители насадок": "Packing retainers",
  "Распределители жидкости": "Liquid distributors",
  "Сборники жидкости": "Liquid collectors",
  "Газожидкостные сепараторы": "Gas-liquid separators",
  "Жидкостные сепараторы/коалесцеры": "Liquid separators / coalescers",
  "Катализаторные корзины": "Catalyst baskets",
  "Массовые кориолисовые": "Coriolis mass flowmeters",
  "Массовые тепловые": "Thermal mass flowmeters",
  "Микроволновые высокочастотные": "High-frequency microwave",
  "Электромагнитные": "Electromagnetic",
  "Ультразвуковые": "Ultrasonic",
  "Радарные и микроволновые": "Radar and microwave",
  "Радарные (с радиолокатором непрерывного излучения с частотной модуляцией)": "Radar (FMCW)",
  "Тарелки клапанные": "Valve trays",
  "Тарелки колпачковые": "Bubble-cap trays",
  "Тарелки ситчатые": "Sieve trays",
  "Седла Берля (керамические)": "Berl saddles (ceramic)",
  "Серии F56 и F57": "F56 and F57 series",
  "Серия F56": "F56 series",
  "Серия F57": "F57 series",
  "Серия FLSTV": "FLSTV series",
  "Серия SV100": "SV100 series",
  "Серия SV200": "SV200 series",
  "Серия SV300": "SV300 series",
  "Серии SV100, SV200, SV300": "SV100, SV200, SV300 series",
  "Регулярные и хаотичные насадки": "Structured and random packings",
  "1–3 поколения": "Generations 1–3",
  "ГОСТ, ASME": "GOST, ASME",
  "ГОСТ, ASME, EN, MSS, FCI": "GOST, ASME, EN, MSS, FCI",
  "ГОСТ, EN, MSS": "GOST, EN, MSS",
  "Пределы допускаемой относительной погрешности измерений объемного расхода и объема жидкости, %": "Max. permissible relative error for liquid volume flow and volume, %",
  "Пределы допускаемой относительной погрешности измерений объемного расхода и объема газа и пара, %": "Max. permissible relative error for gas and steam volume flow and volume, %",
  "± 0.75 (при Re ≥ 20000);": "± 0.75 (at Re ≥ 20000);",
  "± 0.5 (при Re ≥ 20000);": "± 0.5 (at Re ≥ 20000);",
  "± 1.0 (при Re ≥ 20000);": "± 1.0 (at Re ≥ 20000);",
  "± 2.0 (при 10000 < Re < 20000)": "± 2.0 (at 10000 < Re < 20000)",
  "15 ~ 1300 (другие размеры по запросу)": "15 ~ 1300 (other sizes on request)",
  "25 ~ 1200 (другие размеры по запросу)": "25 ~ 1200 (other sizes on request)",
  "стандартный, удлиненный": "standard, extended",
  "ручное; пневмоприводом; электроприводом": "manual; pneumatic; electric",
  "фланцевое по ASME B16.5, ГОСТ 33259-2015; межфланцевое по ASME B16.5, ГОСТ 33259-2015": "flanged ASME B16.5 / GOST 33259-2015; wafer ASME B16.5 / GOST 33259-2015",
  "Яндекс.Карты →": "Yandex Maps →",
  "Дополнительное оборудование": "Additional equipment",
  "Без названия": "Untitled",
  "Дополнительные разделы": "Additional sections",
  "В этом разделе пока нет позиций.": "No items in this section yet.",
  "Продукт не найден.": "Product not found.",
  "Раздел не найден.": "Section not found.",
  "Загрузка…": "Loading…",
  "Каталог": "Catalog"
};
